### ISSUE TITLE
there has a problem...

### ISSUE THREAD

**Issue by 312977** [teerasej/Ionic-Example-SQLite#4]
when i  click  the save or  load  ,thow an exception “Cannot read property 'transaction' of undefined”?thy?   thanks fro your answer

**Comment by teerasej** [comment]
@312977, Please try with latest version of this project.

the key is you need to swap to new SQLite plugin as I updated in the README. you also need to use `ionic state restore` as I mentioned to ensure you will got all important plugins after you clone my repo.
