### ISSUE TITLE
Install not working!

### ISSUE THREAD

**Issue by alouane** [teerasej/Ionic-Example-SQLite#5]
Hi,
I can't install this plugin via command line: `cordova plugin add https://github.com/brodysoft/Cordova-SQLitePlugin.git`
I'm having this error:
`Fetching plugin "https://github.com/brodysoft/Cordova-SQLitePlugin.git" via git clone
Repository "https://github.com/brodysoft/Cordova-SQLitePlugin.git" checked out to git ref "master".
**Error: Unexpected string**`

Is there any other way to install this plugin? Is there some dependencies that should be installed a priori?

**Comment by abdurrahmanekr** [comment]
Try this : cordova plugin add https://github.com/litehelpers/Cordova-sqlite-storage.git

**Comment by alouane** [comment]
Thanks for your answer, but unfortunately I have the same problem:
`....
....
skipping existing file: SQLite3.UWP.vcxproj
skipping existing file: SQLite3.Windows.vcxproj
skipping existing file: SQLite3.WindowsPhone.vcxproj
skipping existing file: Statement.cpp
skipping existing file: Statement.h
skipping existing file: SQLite3.js
skipping existing file: plugin.xml
skipping existing file: tests.js
skipping existing file: SQLitePlugin.js
Error: Unexpected string
`
Every time I'm having this error: `Error: Unexpected string`, I don't know if it is related to my config or something else, but when I check the file: plugins/android.json or plugins/getch.json, I can't fin the sqlite plugin. However, when I add it manuelle inside these files, I get this error: `“sqlite-connector.jar” not found!"`

I checked this [thread](http://stackoverflow.com/questions/37188103/error-while-adding-cordova-plugin-sqlite-connector-jar-not-found), it seems that the problem comes from a dependency: sqlite3 library, 

> This version uses a before_plugin_install hook to install sqlite3 library dependencies from cordova-sqlite-storage-dependencies via npm.

but I don't have any idea on how to install this lib

**Comment by alouane** [comment]
OK, I got it working now
I had to reset the project, build it from scratch, install firstly sqlite plugin, then other plugins and update all libraires
So i guess it has nothing to do with this plugin, juste an incompatibility issue between libs
Thanks!
