### ISSUE TITLE
ionic 2 

### ISSUE THREAD

**Issue by aggreymarsh** [teerasej/Ionic-Example-SQLite#7]
Does this example work with ionic 2 ? if so how do i convert it

**Comment by abdurrahmanekr** [comment]
I made a simple example of this [url](https://github.com/abdurrahmanekr/Ionic-2-Calendar-Example)

**Comment by teerasej** [comment]
The Ionic 2 version is coming soon. Anyway I think @abdurrahmanekr's one is not the latest version of Ionic 2 (according to missing `src` folder) 

After @abdurrahmanekr update the project to latest version I think it'll work ;)
